modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL="https://github.com/SamB440/huge-structure-blocks/issues"
license = "LGPL-3.0"

[[mods]]
modId = "hugestructureblocks"
version = "${version}"
displayName = "Huge Structure Blocks"
authors = "SamB440"
description = '''
Structure blocks. But bigger.
'''
#logoFile = ""

[[dependencies.hugestructureblocks]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hugestructureblocks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "hugestructureblocks.mixins.json"
